apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}

    spec:
      containers:
      - name: application

        image: >-
          {{- if .Values.image.digest }}
          {{ .Values.image.repository }}@{{ .Values.image.digest }}
          {{- else }}
          {{ .Values.image.repository }}
          {{- end }}

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP

        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          {{- toYaml .Values.resources | nindent 12 }}