replicaCount: 1
image:
  repository: mean-application
  digest: sha256:14895f130ba0791ef29e9b100754107d7d6972e554ae5f3de2391e20b4822cfb
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 80
resources: {}
