replicaCount: 1
image:
  repository: tasniimch/mean-client
  digest: sha256:c60f4d9eb0e1a58b2bb643697cc55248e1eba5a443fd4dc09cdc4cb108fd864e
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 80
resources: {}
