replicaCount: 1
image:
  repository: tasniimch/mean-client
  digest: sha256:9bdad49da8869b802886ccd0fa861eac8373caa50feb63327715aeeb343887f2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  targetPort: 80
resources: {}
